"use client"
import * as Tooltip from "@radix-ui/react-tooltip"
import { CheckIcon, ThumbsUp, ThumbsDown, BookOpenText, Sparkle, Sparkles, CopyCheckIcon, CopyIcon } from "lucide-react"
import React, { useState } from "react"

import Typography from "@/components/typography"
import { CreateUserFeedback } from "@/features/chat/chat-services/chat-message-service"
import { useChatContext } from "@/features/chat/chat-ui/chat-context"
import { ChatSentiment, FeedbackType, PromptMessage } from "@/features/chat/models"
import { showError } from "@/features/globals/global-message-store"
import { AI_NAME } from "@/features/theme/theme-config"
import { Button } from "@/features/ui/button"
import { TooltipProvider } from "@/features/ui/tooltip-provider"
import { useWindowSize } from "@/features/ui/windowsize"

import Modal from "./modal"
import RewriteMessageModal from "./rewriteMessageModal"

interface AssistantButtonsProps {
  fleshScore: number
  message: PromptMessage
  onFeedbackChange: (feedback: string) => void
  chatMessageId: string
  chatThreadId: string
}
export const AssistantButtons: React.FC<AssistantButtonsProps> = ({ fleshScore, message, ...props }) => {
  const { iconSize, buttonClass } = useButtonStyles()
  const [copyClicked, setCopyClicked] = useState(false)
  const [thumbsUpClicked, setThumbsUpClicked] = useState(message.sentiment === ChatSentiment.Positive)
  const [thumbsDownClicked, setThumbsDownClicked] = useState(message.sentiment === ChatSentiment.Negative)
  const [feedbackType, setFeedbackType] = useState(message.feedback)
  const [feedbackReason, setFeedbackReason] = useState(message.reason)

  const [isFeedbackModalOpen, setFeedbackModalOpen] = useState(false)
  const { openModal, closeModal } = useChatContext()

  const handleCopyButton = async (): Promise<void> => {
    setCopyClicked(true)
    try {
      const messageWithAttribution = message.content + ("\n\nText generated by " + AI_NAME)
      await navigator.clipboard.writeText(messageWithAttribution)
      props.onFeedbackChange("Message copied to clipboard.")
    } catch (_err) {
      props.onFeedbackChange("Something happened and the message has not been copied.")
    } finally {
      setTimeout(() => {
        props.onFeedbackChange("")
        setCopyClicked(false)
      }, 2000)
    }
  }

  const handleThumbsUpClick = async (): Promise<void> => {
    const previous = { thumbsUpClicked, thumbsDownClicked }
    const sentiment = thumbsUpClicked ? ChatSentiment.Neutral : ChatSentiment.Positive
    setThumbsUpClicked(!previous.thumbsUpClicked)
    setThumbsDownClicked(false)
    try {
      const res = await CreateUserFeedback(props.chatMessageId, FeedbackType.None, sentiment, "", props.chatThreadId)
      if (res.status !== "OK") throw new Error("Failed to submit feedback.")
      const message = "Positive feedback submitted."
      props.onFeedbackChange(message)
      setTimeout(() => props.onFeedbackChange(""), 2000)
    } catch (err) {
      setThumbsUpClicked(previous.thumbsUpClicked)
      setThumbsDownClicked(previous.thumbsDownClicked)
      const error = err instanceof Error ? err.message : typeof err === "string" ? err : "Failed to submit feedback."
      showError(error)
      props.onFeedbackChange(error)
      setTimeout(() => props.onFeedbackChange(""), 2000)
    }
  }

  const handleThumbsDownClick = (): void => {
    setFeedbackModalOpen(true)
    openModal?.()
  }

  const handleFeedbackModalSubmit = async (): Promise<void> => {
    const previous = { thumbsUpClicked, thumbsDownClicked }
    const sentiment = thumbsDownClicked ? ChatSentiment.Neutral : ChatSentiment.Negative
    setThumbsUpClicked(false)
    setThumbsDownClicked(!previous.thumbsDownClicked)
    try {
      const res = await CreateUserFeedback(
        props.chatMessageId,
        feedbackType || FeedbackType.None,
        sentiment,
        (feedbackReason || "").trim(),
        props.chatThreadId
      )
      if (res.status !== "OK") throw new Error("Failed to submit feedback.")
      const message = "Negative feedback submitted."
      setFeedbackType(FeedbackType.None)
      setFeedbackReason("")
      props.onFeedbackChange(message)
      setTimeout(() => props.onFeedbackChange(""), 2000)
      setFeedbackModalOpen(false)
      closeModal?.()
    } catch (_err) {
      setThumbsUpClicked(previous.thumbsUpClicked)
      setThumbsDownClicked(previous.thumbsDownClicked)
      const error = "Failed to submit feedback."
      showError(error)
      props.onFeedbackChange(error)
      setTimeout(() => props.onFeedbackChange(""), 2000)
    }
  }

  const handleFeedbackModalClose = (): void => {
    setFeedbackModalOpen(false)
    closeModal?.()
  }

  return (
    <>
      <div className="flex w-full gap-2">
        <Button
          ariaLabel="Copy text"
          variant={"ghost"}
          size={"default"}
          className={`${buttonClass} ${copyClicked ? "bg-button text-buttonText" : ""}`}
          title="Copy text"
          onClick={handleCopyButton}
        >
          {copyClicked ? <CopyCheckIcon size={iconSize} /> : <CopyIcon size={iconSize} />}
        </Button>

        <Button
          variant={"positive"}
          size={"default"}
          className={`${buttonClass} ${thumbsUpClicked ? "bg-success text-buttonText" : ""}`}
          title="Thumbs up"
          onClick={handleThumbsUpClick}
          ariaLabel="Provide positive feedback"
        >
          {thumbsUpClicked ? <CheckIcon size={iconSize} /> : <ThumbsUp size={iconSize} />}
        </Button>

        <Button
          variant={"negative"}
          size={"default"}
          className={`${buttonClass} ${thumbsDownClicked ? "bg-destructive" : ""}`}
          title="Thumbs down"
          onClick={handleThumbsDownClick}
          ariaLabel="Provide negative feedback"
        >
          {thumbsDownClicked ? <CheckIcon size={iconSize} /> : <ThumbsDown size={iconSize} />}
        </Button>

        <RewriteMessageButton fleshScore={fleshScore} message={message} {...props} />

        <FleschButton fleschScore={fleshScore} />
      </div>
      <Modal
        chatThreadId={props.chatThreadId}
        chatMessageId={props.chatMessageId}
        feedbackType={feedbackType}
        onFeedbackTypeChange={setFeedbackType}
        feedbackReason={feedbackReason}
        onFeedbackReasonChange={setFeedbackReason}
        open={isFeedbackModalOpen}
        onClose={handleFeedbackModalClose}
        onSubmit={handleFeedbackModalSubmit}
      />
    </>
  )
}

const useButtonStyles = (): { iconSize: number; buttonClass: string } => {
  const { width } = useWindowSize()
  let iconSize = 10
  let buttonClass = "h-9"

  if (width < 768) {
    buttonClass = "h-7"
  } else if (width >= 768 && width < 1024) {
    iconSize = 12
  } else if (width >= 1024) {
    iconSize = 16
  }

  return { iconSize, buttonClass }
}

export const RewriteMessageButton: React.FC<AssistantButtonsProps> = ({ fleshScore, message, ...props }) => {
  const { iconSize, buttonClass } = useButtonStyles()

  const [isRewriteMessageModalOpen, setIsRewriteMessageModalOpen] = useState(false)
  const [rewriteClicked, setRewriteClicked] = useState(false)
  const { openModal, closeModal } = useChatContext()

  const handleRewriteWithSuggestions = (): void => {
    setRewriteClicked(true)
    setIsRewriteMessageModalOpen(true)
    openModal?.()
  }

  const handleRewriteModalSubmit = (): void => {
    // TODO: Populate chat input OR send message to chatbot directly
    setRewriteClicked(false)
    setIsRewriteMessageModalOpen(false)
    closeModal?.()
  }

  const handleRewriteModalClose = (): void => {
    setRewriteClicked(false)
    setIsRewriteMessageModalOpen(false)
    closeModal?.()
  }
  return (
    <>
      <Button
        ariaLabel="Rewrite with suggestions"
        variant={"ghost"}
        size={"default"}
        className={`${buttonClass} ${rewriteClicked ? "bg-button text-buttonText" : ""}`}
        title="Rewrite with suggestions"
        onClick={handleRewriteWithSuggestions}
      >
        {rewriteClicked ? <Sparkles size={iconSize} /> : <Sparkle size={iconSize} />}
      </Button>
      <RewriteMessageModal
        chatThreadId={props.chatThreadId}
        chatMessageId={props.chatMessageId}
        open={isRewriteMessageModalOpen}
        rewriteAction={getRewriterAction(fleshScore, !!message.contentFilterResult)}
        message={message.content}
        onClose={handleRewriteModalClose}
        onSubmit={handleRewriteModalSubmit}
      />
    </>
  )
}

const getRewriterAction = (score: number, contentFilter: boolean): "Simplify" | "Improve" | "Explain" => {
  if (contentFilter) return "Explain"
  if (score > 8) return "Simplify"
  if (score <= 8) return "Improve"
  return "Improve"
}

interface FleschButtonProps {
  fleschScore: number
}
const FleschButton: React.FC<FleschButtonProps> = ({ fleschScore }) => {
  const { iconSize } = useButtonStyles()

  return (
    <TooltipProvider>
      <Tooltip.Root delayDuration={0}>
        <Tooltip.Trigger className="relative flex w-full items-center justify-center gap-4 rounded-md px-2 hover:bg-accent hover:text-buttonText">
          <div className="flex items-center justify-center gap-2">
            <BookOpenText size={iconSize} />
            {fleschScore}
          </div>
        </Tooltip.Trigger>
        <Tooltip.Content
          side="top"
          className="z-20 rounded-md bg-primary-foreground px-4 py-2 text-foreground shadow-lg"
        >
          <Typography variant="p">
            <strong>Flesch-Kincaid Score (KFKS):</strong> The Flesch-Kincaid Score below shows
            <br />
            how easy or difficult it is to understand the writing.
            <br /> The higher the score, the more difficult it is to read.
            <br />
            Aim for a score of <strong>8</strong> to make sure most people find the message clear.
            <br />
            This includes younger readers and those who are still learning English.
          </Typography>
        </Tooltip.Content>
      </Tooltip.Root>
    </TooltipProvider>
  )
}
